### ISSUE TITLE
WooCommerce require LONGBLOB

### ISSUE THREAD

**Issue by killua99** [preinheimer/xhprof#110]
More than an issue is something to update.

MySQL require LONGBLOB to save data for WooCommerce sites (WordPress plugin that transform a simple blog into a webstore, for those who doesn't know).

Also the server_id is `server_id char(3) NOT NULL default 't11',` when it need to be longer also.

**Comment by aik099** [comment]
> MySQL require LONGBLOB to save data for WooCommerce sites (WordPress plugin that transform a simple blog into a webstore, for those who doesn't know).

This means, that you have a lots of profiling data I guess.

> Also the server_id is `server_idchar(3) NOT NULL default 't11'`, when it need to be longer also.

Any example values that goes in there?

You're welcome to send PR with a fixes.

**Comment by killua99** [comment]
My server id is, `vm.local`

Yes, I'm confuse if this case need a PR, what are your thoughts ?

**Comment by aik099** [comment]
If you want to change library code, then this is done via PR creation 😉 

There are plenty docs online about how to create PR (pull request) if you haven't done this before.
