### ISSUE TITLE
It would be nice to simple download and run

### ISSUE THREAD

**Issue by killua99** [preinheimer/xhprof#111]
Now when you have the entire environment ready to run XHprof this package require some minor manual setup, like copy a file etc, would be nice to have a composer post install script where it copy the config files and also when you run the site for first time it see no table exists it create it automatically if the user can. If not, a nice message will show telling the cause the site isn't ready yet.

Before submitting anything I prefer to create this issue to discuss and then write the code properly.

**Comment by aik099** [comment]
> Now when you have the entire environment ready to run XHprof this package require some minor manual setup, like copy a file etc

Yes, these steps are described in README.md.

> ... would be nice to have a composer post install script where it copy the config files and also when you run the site for first time it see no table exists it create it automatically if the user can.

You don't install this package via Composer, but rather git clone directly in Web Server's Document Root (at least this is what I do), so no `composer post install scripts`. Upon each run doing checks for missing DB table and creating it is not worth it IMO.
