### ISSUE TITLE
Adding index.php to links

### ISSUE THREAD

**Issue by ip512** [preinheimer/xhprof#64]
If my web server is not configured to use index.php as default file (which is the case sometimes on nginx) some links doesn't work correctly (links on parent and child functions).
I think it can easily be fixed by changing "$base_path/?" by "$base_path/index.php?" in display/xhprof.php file.
It should not make any trouble on existing installation.

**Comment by aik099** [comment]
Sure. Please send a PR.

**Comment by ip512** [comment]
I close the issue since PR #72 has not been merged
