### ISSUE TITLE
Warnings during request display on single run page

### ISSUE THREAD

**Issue by aik099** [preinheimer/xhprof#86]
The page call I was profiling was a form submit of 3 dimensional array. The code, that prints it https://github.com/preinheimer/xhprof/blob/master/xhprof_lib/templates/single_run_header_block.phtml#L132 presumes that array can't contain sub-arrays in it and uses `implode` on it. That in turn triggers a warning about `array to string conversion`.

I'm willing to make a PR with a fix, but currently the only idea I have is to display `print_r` output instead of doing `implode`.

**Comment by aik099** [comment]
@preinheimer ping.

**Comment by preinheimer** [comment]
So we've got a few options I guess. 

* Ignore nested data, assume that there's enough data to help understand what's happening in the top layer
* Write some recursive code to display it in a pretty fashion
* Display something lame like `serialize(var)`
* Display the data in something like json, which would handle nested forms nicely, but if it was an ajax request sending in actual json it would get confusing. 

Recursion seems like the most work, and the most useful :/

**Comment by aik099** [comment]
PR created.
